In [2]:
import numpy as np

In [4]:
#  1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [55]:
threeD_arr = np.random.randint(1,101,(3,3))
threeD_arr

array([[14, 20, 81],
       [91, 34, 46],
       [77,  7, 57]], dtype=int32)

In [56]:
threeD_arr.T

array([[14, 91, 77],
       [20, 34,  7],
       [81, 46, 57]], dtype=int32)

In [13]:
# 2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [15]:
arr1 = np.array([i for i in range(1,11)])

arr1.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [20]:
array_4x4 = np.random.rand(4, 4)

array_6x6 = np.zeros((6, 6))


array_6x6[1:5, 1:5] = array_4x4

print("Original 4x4 array:")
print(array_4x4)
print("\n6x6 array with border of zeros:")
print(array_6x6)


Original 4x4 array:
[[0.31543679 0.69728746 0.73110292 0.2503884 ]
 [0.62612475 0.43946337 0.49354693 0.36649965]
 [0.29200383 0.01669974 0.18484576 0.54503257]
 [0.55164061 0.84957744 0.71697248 0.62762399]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.31543679 0.69728746 0.73110292 0.2503884  0.        ]
 [0.         0.62612475 0.43946337 0.49354693 0.36649965 0.        ]
 [0.         0.29200383 0.01669974 0.18484576 0.54503257 0.        ]
 [0.         0.55164061 0.84957744 0.71697248 0.62762399 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [21]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [22]:
np.array([i for i in range(10,60,5)])

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [23]:
#  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
# (uppercase, lowercase, title case, etc.) to each element.

In [37]:
arr = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(arr)
lower_case = np.char.lower(arr)
title_case = np.char.title(arr)
swap_case = np.char.swapcase(arr)

print(upper_case,lower_case,title_case,swap_case)

['PYTHON' 'NUMPY' 'PANDAS'] ['python' 'numpy' 'pandas'] ['Python' 'Numpy' 'Pandas'] ['PYTHON' 'NUMPY' 'PANDAS']


In [38]:
# Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [39]:
import numpy as np


words = np.array(["hello", "numpy", "array"])

spaced_words = np.char.join(" ", words)

print("Original words:", words)
print("Words with spaces:", spaced_words)


Original words: ['hello' 'numpy' 'array']
Words with spaces: ['h e l l o' 'n u m p y' 'a r r a y']


In [41]:
# Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [40]:
import numpy as np


array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[1, 3], [5, 7]])


addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2  

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[2 4]
 [6 8]]

Array 2:
[[1 3]
 [5 7]]

Element-wise Addition:
[[ 3  7]
 [11 15]]

Element-wise Subtraction:
[[1 1]
 [1 1]]

Element-wise Multiplication:
[[ 2 12]
 [30 56]]

Element-wise Division:
[[2.         1.33333333]
 [1.2        1.14285714]]


In [42]:
# Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [44]:
fiv_arr = np.ones((5,5))
fiv_arr.diagonal()

array([1., 1., 1., 1., 1.])

In [45]:
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
# this array.

In [53]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_numbers = np.random.randint(0, 1001, 100)

prime_numbers = np.array([num for num in random_numbers if is_prime(num)])

print("Random Numbers Array:")
print(random_numbers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Numbers Array:
[221  12 816 965 828 548 498 269 853 177 839 320 195 189 664 158 806 919
 757 757 113 821 646 949 570 204 772 331 360 442 183 936 709 638 476 553
 330 227  72 214 789 657 715 367 953 812 709 788 601 296 920 899 598 773
 529 350  23 351 964  36 274 712 669 385 467 161 609 670 757 462 109 650
 346 155 149 464 770   7 581 197 255  73 860 928 813 739 560 231 877 724
 876 505  46  52 837 345 526 268 247 575]

Prime Numbers in the Array:
[269 853 839 919 757 757 113 821 331 709 227 367 953 709 601 773  23 467
 757 109 149   7 197  73 739 877]


In [46]:
#  10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
# averages

In [57]:
import numpy as np

temps = np.random.randint(60, 100, 30)
weekly_averages = [np.mean(temps[i:i+7]) for i in range(0, len(temps), 7)]
print("Daily Temperatures:", temps)
print("Weekly Averages:", weekly_averages)


Daily Temperatures: [99 66 72 66 77 93 86 75 64 61 77 73 83 75 70 67 69 81 74 78 62 65 84 82
 70 78 94 88 61 85]
Weekly Averages: [np.float64(79.85714285714286), np.float64(72.57142857142857), np.float64(71.57142857142857), np.float64(80.14285714285714), np.float64(73.0)]
